# Generated by Django 4.2.1 on 2023-10-07 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0005_remove_agent_customer_agent_user_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='User_Agent',
        ),
    ]
